# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    admin.address:
        class: AppBundle\Admin\AddressAdmin
        arguments: [~, AppBundle\Entity\Address, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Address }

    admin.type:
        class: AppBundle\Admin\TypeAdmin
        arguments: [~, AppBundle\Entity\Type, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Type }
